/* generated by bin2h, do not edit */

extern unsigned char binary_boot_bin[512];
extern unsigned char binary_bootboot_bin[11776];
extern unsigned char binary_bootboot_efi[95926];
extern unsigned char binary_bootboot_img[34616];
extern unsigned char binary_LICENCE_broadcom[1594];
extern unsigned char binary_bootcode_bin[52480];
extern unsigned char binary_fixup_dat[7274];
extern unsigned char binary_start_elf[3000960];
